# Root directory for Air to watch
root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
  # Output binary location
  bin = "./bin/main"
  # Build command for your API
  cmd = "go build -o ./bin/main ./cmd/api"
  # Delay after file change before rebuilding (ms)
  delay = 1000

  # Directories and files to ignore
  exclude_dir = ["assets", "bin", "vendor", "testdata", "web", "docs", "scripts"]
  exclude_regex = ["_test.go"] # ignore test files
  exclude_unchanged = false

  # Extensions to watch
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Run before build (auto‑generate docs)
  pre_cmd = ["make gen-docs"]

  # Log build errors here
  log = "build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[env]
# Default environment for local dev
APP_ENV = "development"
